<?php

$callerId = $block->getData('caller_id');
$callerData = $block->getCallerData($callerId);
$title = $block->toOptionArray();
?>
<?php if(!empty($callerData)):?>
<div class="edit-profile edit-prof-popup">
    <form class="edit-caller-profile-<?=$callerId;?>" action="<?= $block->getUrl('loginascustomer/index/savecaller');?>" method="post" id="form-validate" autocomplete="off" data-mage-init='{"validation": {}}'>
        <button type="button" class="action submit primary edt-top-btn save-caller" id="<?=$callerId;?>" title="<?= $escaper->escapeHtmlAttr(__('Save')) ?>">
            <span><?= $escaper->escapeHtml(__('Save')) ?></span>
        </button>
        <div class="fields">
            <h3 class="edt-d-tit"><?= $block->escapeHtml("Details");?></h3>
            <input type="hidden" name="child_id" value="<?= $block->escapeHtml($callerId);?>">
            <input type="hidden" name="consent_id" value="<?=$callerData[0]['consent_id']?>" />
            <fieldset class="fieldset edit info">
                <div class="control">
                    <div class="field title">
                        <select name="title">
                            <?php foreach ($title as $value):?>
                                <option value="<?= $block->escapeHtml($value['label']);?>" <?php if($callerData[0]['title']==$value['label']) echo "selected" ?>><?= $block->escapeHtml($value['label']);?></option>
                            <?php endforeach;?>
                        </select>
                    </div>
                </div>
                <div class="control">
                    <div class="field firstname">
                        <input id="firstname-<?=$callerId;?>" type="text" name="firstname" value="<?= $block->escapeHtml($callerData[0]['firstname']);?>" title="<?= $block->escapeHtml("Firstname");?>" class="input-text" placeholder = "<?= $block->escapeHtml("Firstname");?>" data-validate="{required:true}" data-msg-required="First name can't be empty" autocomplete="off" aria-required="true" maxlength="50" /> 
                    </div>
                    <div class="field lastname">
                        <input id="lastname-<?=$callerId;?>" type="text" name="lastname" value="<?= $block->escapeHtml($callerData[0]['lastname']);?>" title="<?= $block->escapeHtml("Lastname");?>" class="input-text" placeholder="<?= $block->escapeHtml("Lastname");?>" data-validate="{required:true}" data-msg-required="Last name can't be empty" autocomplete="off" aria-required="true" maxlength="50" />
                    </div>
                </div>
                <div class="control-center">
                    <div class="control">
                        <div class="field phone-number">
                            <input type="text" name="phone_no" value="<?= $block->escapeHtml($callerData[0]['phone_no']);?>" title="<?= $block->escapeHtml("Phone Number");?>" class="input-text" placeholder="<?= $block->escapeHtml("Phone Number");?>" maxlength="15" />
                        </div>
                        <div class="field alternate-phone-number">
                            <input type="text" name="alt_phone_no" value="<?= $block->escapeHtml($callerData[0]['alt_phone_no']);?>" title="<?= $block->escapeHtml("Alternate Phone Number");?>" class="input-text" placeholder="<?= $block->escapeHtml("Alternate Phone Number");?>" maxlength="15" />
                        </div>
                    </div>
                    <div class="control">
                        <div class="field email">
                            <input type="text" name="email" value="<?= $block->escapeHtml($callerData[0]['email']);?>" title="<?= $block->escapeHtml("Email");?>" class="input-text" placeholder="<?= $block->escapeHtml("Email");?>" data-validate="{'validate-email':true}" data-msg-validate-email="Email is not a valid email" maxlength="320" />
                        </div>
                        <?php $customer = $block->customerExists($callerData[0]['email']);?>
                        <?php if (!$customer):?>
                            <div class="field is_setup_online_account">
                                <input type="checkbox"
                                name="is_setup_online_account"
                                title="<?= $escaper->escapeHtmlAttr(__('Set up online account')) ?>"
                                value="1"
                                id="is_setup_online_account_<?=$callerId?>"
                                />
                            <label for="is_setup_online_account_<?=$callerId?>" class="label">
                                <?= $escaper->escapeHtml(__('Set up online account')) ?>
                            </label>
                            </div>
                        <?php endif;?>
                    </div>
                </div>
                <p class="postcode-error" style="display:none; color:red">Please Enter Valid Postcode</p>
                <div class="control">
                    <div class="field postcode">
                        <input type="text" name="postcode" value="<?= $block->escapeHtml($callerData[0]['postcode']);?>" title="<?= $block->escapeHtml("Postcode");?>" class="input-text" id="Postcode_1" placeholder="<?= $block->escapeHtml("Postcode");?>" data-validate="{'required':true, 'validate-zip-international':true}"
                       data-msg-required="Post code can't be empty" maxlength="8" oninput="this.value = this.value.toUpperCase()" />
                    </div>
                </div>
            </fieldset>
            </div>
            <div class="consent" id="element"
            data-mage-init='{"accordion":{"openedState": "active", "collapsible": true, "active": [], "multipleCollapsible": true}}'>
            <div class="prof-title-acco" data-role="collapsible">
                <div class="pls-mins plusico">
                    <svg role="img" width="20" height="20">
                        <use xlink:href="#plus-solid"></use>
                    </svg>
                </div>
                <div class="pls-mins minico">
                    <svg role="img" width="20" height="20">
                        <use xlink:href="#minus-solid"></use>
                    </svg>
                </div>
            <h3><?= $block->escapeHtml("Consent");?></h3>
            </div>
        <div data-role="content">
           <?php 
            $allMarketing=0;
            $allCorrespondence=0;
            $email=0;
            $newsletter=0;
            $product=0;
            $sms=0;
            $telephone=0;
            $directMail=0;
            $telephone_service = 0;
            $telephone_marketing = 0;
            if($callerData[0]['consent_id']){
                $consentData = $block->getConsentData($callerData[0]['consent_id']);
                $allMarketing = $consentData->getData('opt_out_all_marketing');
                $allCorrespondence = $consentData->getData('opt_out_all_correspondence');
                $email = $consentData->getData('email');
                $newsletter = $consentData->getData('newsletter_email');
                $product = $consentData->getData('product_n_service_email');
                $sms = $consentData->getData('sms');
                $telephone = $consentData->getData('telephone');
                $directMail = $consentData->getData('direct_mail');
                $telephone_service = $consentData->getData('market_pref_telephone_service');
                $telephone_marketing = $consentData->getData('market_pref_telephone_marketing');
                
            }
            
            ?>
            <div class="consent-inner">
            <ul>
                <li>
                    <input id="caller_edit_marketing_<?=$callerId?>" type="checkbox" name="opt_out_all_marketing" value="1" <?php if($allMarketing){echo "checked";}?> class="caller_marketing" />
                    <label for="caller_edit_marketing_<?=$callerId?>"><?= $block->esCapeHtml("Opt-out of all marketing")?></label>
                </li>
                <li>
                    <input id="caller_edit_email_<?=$callerId?>" type="checkbox" name="consent_email" value="1" <?php if($email){echo "checked";}?> class="group caller-email" />
                    <label for="caller_edit_email_<?=$callerId?>"><?= $block->esCapeHtml("Email")?></label>
                    <div class="cont-bl-in">
                        <div class="consent-check">
                            <input id="caller_edit_newsletter_<?=$callerId?>" type="checkbox" name="newsletter" value="1" <?php if($newsletter){echo "checked";}?> class="group caller-email-box caller-newsletter" />
                            <label for="caller_edit_newsletter_<?=$callerId?>"><?= $block->esCapeHtml("Newsletter")?></label>
                        </div>
                        <div class="consent-check">
                            <input id="caller_edit_product_<?=$callerId?>" type="checkbox" name="product" value="1" <?php if($product){echo "checked";}?> class="group caller-email-box caller-productandservice" />
                            <label for="caller_edit_product_<?=$callerId?>"><?= $block->esCapeHtml("Product and services")?></label>
                        </div>
                    </div>
                </li>

                <li>
                    <input id="caller_edit_sms_<?=$callerId?>" type="checkbox" name="sms" value="1" <?php if($sms){echo "checked";}?> class="group" />
                    <label for="caller_edit_sms_<?=$callerId?>"><?= $block->esCapeHtml("SMS")?></label>
                </li>

                <li>
                    <input id="caller_edit_telephone_<?=$callerId?>" type="checkbox" name="telephone" value="1" <?php if($telephone){echo "checked";}?> class="group caller_edit_telephone" />
                    <label for="caller_edit_telephone_<?=$callerId?>"><?= $block->esCapeHtml("Telephone")?></label>
                    <div class="cont-bl-in">
                        <div class="consent-check">
                            <input id="caller_edit_telephone_service_<?=$callerId?>" type="checkbox" name="market_pref_telephone_service" value="1" <?php if($telephone_service){echo "checked";}?> class="group prof_edit_tel_child caller_edit_tel_ser" />
                            <label for="caller_edit_telephone_service_<?=$callerId?>"><?= $block->esCapeHtml("Service")?></label>
                        </div>
                        <div class="consent-check">
                            <input id="caller_edit_telephone_marketing_<?=$callerId?>" type="checkbox" name="market_pref_telephone_marketing" value="1" <?php if($telephone_marketing){echo "checked";}?> class="group prof_edit_tel_child caller_edit_tel_mark" />
                            <label for="caller_edit_telephone_marketing_<?=$callerId?>"><?= $block->esCapeHtml("Marketing")?></label>
                        </div>
                    </div>
                </li>

                <li>
                    <input id="caller_edit_direct_mail_<?=$callerId?>" type="checkbox" name="direct_mail" value="1" <?php if($directMail){echo "checked";}?> class="group" />
                    <label for="caller_edit_direct_mail_<?=$callerId?>"><?= $block->esCapeHtml("Direct mail")?></label>
                </li>
                <li>
                    <input id="caller_edit_correspondence_<?=$callerId?>" type="checkbox" name="opt_out_all_correspondence" value="1" <?php if($allCorrespondence){echo "checked";}?> class="caller_correspondence"/>
                    <label for="caller_edit_correspondence_<?=$callerId?>"><?= $block->esCapeHtml("Opt-out of all correspondence")?></label>
                </li>
            </ul>
        </div>
        </div>
    </div>
        
        <div class="actions-toolbar sticky-btm-mod-btn">
        <div class="caller-message" id="caller-message" style="display: none;"></div>
            <div class="primary">
                <button id="<?=$callerId;?>" type="button"
                    class="action submit primary save-caller"
                    title="<?= $escaper->escapeHtmlAttr(__('Save')) ?>">
                    <span><?= $escaper->escapeHtml(__('Save')) ?></span>
                </button>
            </div>
            <div class="secondary">
                <a class="action secondary"
                   href="#">
                    <?= $escaper->escapeHtml(__('Deactivate account')) ?>
                </a>
            </div>
        </div>
    </form>
</div>
<script type="text/javascript">
require(["jquery",'mage/validation'], function($) {
    
    var dataForm = $('#form-validate');
    var ignore = null;

    dataForm.mage('validation', {
        ignore: ignore ? ':hidden:not(' + ignore + ')' : ':hidden'
    }).find('input:text').attr('autocomplete', 'off');

    $(document).on('click', '.caller-newsletter', function () {
        if($(this).is(":checked")) {
            $('.caller-email').prop('checked', true);
            $(this).prop('checked', true);
        }else{
            if(!$('.caller-productandservice').is(":checked")) {
                $('.caller-email').prop('checked', false);
            }
            $(this).prop('checked', false);
        }   
    });

    $(document).on('click', '.caller-productandservice', function () {
        if($(this).is(":checked")) {
            $('.caller-email').prop('checked', true);
            $(this).prop('checked', true);
        }else{
            if(!$('.caller-newsletter').is(":checked")) {
                $('.caller-email').prop('checked', false);
            }
            $(this).prop('checked', false);
        }   
    });

    $(document).on('click', '.caller_marketing', function () {
        if($(this).is(":checked")) {
            $('.group').prop('checked', false);
            $('.caller_correspondence').prop('checked', false);
            $(this).prop('checked', true);
        }   
    });

     $(document).on('click', '.caller-email', function () {
        if($(this).is(":checked")) {
            $('.caller-email-box').prop('checked', true);
            $(this).prop('checked', true);
        }else{
            $('.caller-email-box').prop('checked', false);
            $(this).prop('checked', false);
        }   
    });

    $(document).on('click', '.group', function () {
        
        if($(this).is(":checked")) {
            $('.caller_marketing').prop('checked', false);
            $('.caller_correspondence').prop('checked', false);
            $(this).prop('checked', true);
        }   
    });

    $(document).on('click', '.caller_correspondence', function () {
           if($(this).is(":checked")) {
               $('.caller_marketing').prop('checked', false);
               $('.group').prop('checked', false);
               $(this).prop('checked', true);
           }   
    });

    $('body').on('click', '.action.primary.save-caller', function(e){
        var flag = dataForm.validation('isValid'); //validates form and returns boolean
        var id = $(this).attr('id');
        if (flag) {
            e.preventDefault();
            e.stopImmediatePropagation();
            $.ajax({
                type: 'post',
                url: '<?php echo $block->getUrl('loginascustomer/index/savecaller');?>',
                data: $(".edit-caller-profile-"+id).serialize(),
                cache: false,
                showLoader: 'true',
                success: function(response) {
                    if(response.message) {
                    $('.caller-message').show();
                    $('.caller-message').html(response.message);
                    $('.caller-message').css('color','red');
                    
                    } else {
                        var name = $("#firstname-"+id).val()+" "+$("#lastname-"+id).val();
                        $(".link-acde-left #"+id).html(name);
                        var modelId = "#"+$(".caller-"+id).data("id");
                        $(modelId).modal("closeModal");
                    } 
                        
                }
            });
            return false;
        }
    });
    $('#Postcode_1').on('input', function(){
                var regexp = /^[A-Z]{1,2}[0-9RCHNQ][0-9A-Z]?\s?[0-9][ABD-HJLNP-UW-Z]{2}$|^[A-Z]{2}-?[0-9]{4}$/;
                var postcode = $('#Postcode_1').val();
                var zipcode = postcode.toUpperCase();
                if(regexp.test(zipcode)){
                    $('.postcode-error').hide();
                    $('.save-caller').attr('disabled', false);
                }
                else{
                    $(".postcode-error").show();
                    $('.save-caller').attr('disabled', 'disabled');
                }
            });
    $(document).on('click', '.caller_edit_telephone', function () {
           if($(this).is(":checked")) {
               $('.caller_edit_tel_mark').prop('checked', true);
               $('.caller_edit_tel_ser').prop('checked', true);
           }else{
               $('.caller_edit_tel_mark').prop('checked', false);
               $('.caller_edit_tel_ser').prop('checked', false);
           }   
       });
       $(document).on('click', '.caller_edit_tel_mark, .caller_edit_tel_ser', function () {
           if($(this).is(":checked")) {
               $('.caller_edit_telephone').prop('checked', true);
           }else{
                if(!$('.caller_edit_tel_ser').is(":checked") && !$('.caller_edit_tel_mark').is(":checked")) {
                    $('.caller_edit_telephone').prop('checked', false);               
                }   
           }   
       });

});
</script>
<?php endif;?>
